// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoalaCodeFirst.Models;

#nullable disable

namespace ScoalaCodeFirst.Migrations
{
    [DbContext(typeof(ScoalaDbContext))]
    partial class ScoalaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScoalaCodeFirst.Models.Clasa", b =>
                {
                    b.Property<int>("ClasaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClasaID"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("NrElevi")
                        .HasColumnType("int");

                    b.HasKey("ClasaID");

                    b.ToTable("Clase");
                });

            modelBuilder.Entity("ScoalaCodeFirst.Models.Elev", b =>
                {
                    b.Property<int>("ElevID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElevID"));

                    b.Property<int>("ClasaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataNasterii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ElevID");

                    b.HasIndex("ClasaID");

                    b.ToTable("Elevi");
                });

            modelBuilder.Entity("ScoalaCodeFirst.Models.Elev", b =>
                {
                    b.HasOne("ScoalaCodeFirst.Models.Clasa", "Clasa")
                        .WithMany("Elevi")
                        .HasForeignKey("ClasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clasa");
                });

            modelBuilder.Entity("ScoalaCodeFirst.Models.Clasa", b =>
                {
                    b.Navigation("Elevi");
                });
#pragma warning restore 612, 618
        }
    }
}
